print("Welcome to the tip calculator.")
amount_str = input("What was the total bill? $")
amount = float(amount_str)
percent_str = input("What percentage tip would you like to give? 10, 12, or 15? ")
percent = int(percent_str)
num_people_str = input("How many people to split the bill? ")
num_people = int(num_people_str)
total = amount + (amount * percent/100)
split = round(total / num_people, 2)
print("Each person should pay: ${:.2f}".format(split))